---

# Author: Daniele Rondina, geaaru@gmail.com
# Description: Create Sabayon node with pam_radius module to test terminal
#              connection.

- name: "Prepare Terminal tester node with pam_radiusd"
  debug:
    msg: "Terminal test nodes: {{ pam_radiusd_nodes }} with profiles {{ freeradius_lxd_profiles }}"

- name: "Create a LXD Terminal test Container"
  vars:
    profiles: "{{ freeradius_lxd_profiles | list }}"
    lxd_image: "{{ freeradius_lxd_image }}"
    node_name: "{{ item }}"
  include_role:
    name: lxd
    tasks_from: create_container
  with_items:
    - "{{ pam_radiusd_nodes }}"
  tags:
    - create_terminal_container

# Configure pam authentication 
- name: Configure pam stuff
  include_role:
    name: freeradius
    tasks_from: configure-terminal-node
  loop_control:
    loop_var: container
  with_items:
    - "{{ pam_radiusd_nodes }}"
