---

# Author: Daniele Rondina, geaaru@gmail.com
# Description: 

- name: "Prepare MySQL Cluster nodes"
  debug:
    msg: "Nodes to build: {{ mysql_nodes }} with profiles {{ mysql_lxd_profiles }}"

- name: "Create a LXD MySQL Container"
  vars:
    profiles: "{{ mysql_lxd_profiles | list }}"
    lxd_image: "{{ mysql_server_lxd_image }}"
    node_name: "{{ item }}"
  include_role:
    name: lxd
    tasks_from: create_container
  with_items:
    - "{{ mysql_nodes }}"
  tags:
    - create_mysql_container

- name: Configure MySQL Cluster
  include_role:
    name: mysql
    tasks_from: configure
  loop_control:
    loop_var: container
  with_items:
    - "{{ mysql_nodes }}"
  tags:
    - initialize_mysql_cluster

- name: Create Cluster from first node
  include_role:
    name: mysql
    tasks_from: create_cluster
  vars:
    container: "{{ mysql_nodes[0] }}"
  tags:
    - create_mysql_cluster

- name: Create Database from first node
  include_role:
    name: mysql
    tasks_from: create_database
  vars:
    container: "{{ mysql_nodes[0] }}"
  tags:
    - create_mysql_database

- name: "Create LXD MySQL Router Container"
  vars:
    profiles: "{{ mysql_lxd_profiles | list }}"
    lxd_image: "{{ mysql_server_lxd_image }}"
    node_name: "{{ item }}"
  include_role:
    name: lxd
    tasks_from: create_container
  with_items:
    - "{{ mysql_router_nodes }}"
  tags:
    - create_mysql_router_container

- name: Configure MySQL Router
  include_role:
    name: mysql
    tasks_from: configure_router
  with_items:
    - "{{ mysql_router_nodes }}"
  loop_control:
    loop_var: container
  tags:
    - configure_mysql_router
