---

# Author: Daniele Rondina, geaaru@gmail.com
# Description: Create LXD container for simulate Access Point

- name: "Prepare FreeRadius nodes"
  debug:
    msg: "Freeradius nodes {{ freeradius_nodes }} with profiles {{ freeradius_lxd_profiles }}"

- name: "Create LXD AP Simulator Container"
  vars:
    profiles: "{{ freeradius_lxd_profiles | list }}"
    lxd_image: "{{ freeradius_lxd_image }}"
    node_name: "{{ item }}"
  include_role:
    name: lxd
    tasks_from: create_container
  with_items:
    - "{{ ap_simulator_nodes }}"
  tags:
    - create_ap_simulator_nodes

- name: Execute command
  shell: lxc exec {{ freeradius_container }} -- sleep 2 && ip a
  loop_control:
    loop_var: freeradius_container
  with_items:
    - "{{ freeradius_nodes }}"

