---

- hosts:
    - all
  # Execute playbook this this env for have more user friendly output.
  #  ANSIBLE_STDOUT_CALLBACK=debug
  #  LXD_INSECURE_TLS=1
  environment:
    - PATH: "{{ ansible_env.PATH }}:{{ dbrm_path }}"
    - OVERRIDE_LOCAL_CONFIG_FILE: "{{ dbrm_config_dir }}/dbrm.conf"
    - DBRM_VERBOSE: 1

  tasks:

    - name: Build Freeradius Environment
      block:

        # Create MySQL Cluster
        - name: Build
          include_role:
            name: lxd
            tasks_from: image_builder_mysql
          tags:
            - build_mysql_nodes

        # Create FreeRadius Cluster
        - name: Build
          include_role:
            name: lxd
            tasks_from: image_builder
          tags:
            - build_freeradius_nodes

        # Initialize Freeradius Database
        - name: Initialize Database
          include_role:
            name: mysql
            tasks_from: initialize_freeradius_db
          tags:
            - initialize_freeradius_db

        # Create terminator container module
        - name: Create Terminal Container
          include_role:
            name: lxd
            tasks_from: image_builder_terminal_node
          tags:
            - build_terminal_nodes

