---

# Author: Daniele Rondina, geaaru@sabayonlinux.org
# Description: Configure Freeradius Nodes


- name: "{{ container }}: Create systemd override directory"
  shell: lxc exec {{ container }} -- mkdir -p /etc/systemd/system/freeradius.service.d

- name: "{{ container }}: Create staging directory if doesn't exist"
  file:
    path: "{{ staging_dir }}/{{ container }}"
    state: directory
    mode: '0755'

- name: "{{ container }}: Process FreeRadius Config templates"
  template:
    src: "{{ freeradius_config_dir }}/{{ freeradius_instance_name }}/{{ tpl.source }}"
    dest: "{{ freeradius_config_dir }}/{{ freeradius_instance_name }}/{{ tpl.dst }}"
  loop_control:
    loop_var: tpl
  with_items:
    - "{{ freeradius_config_templates }}"
  when: freeradius_config_templates is defined

- name: "{{ container }}: Prepare systemd override file"
  template:
    src: override-systemd.conf
    dest: "{{ staging_dir }}/{{ container }}/override.conf"

- name: "{{ container }}: Push file override.conf"
  shell: lxc file push {{ staging_dir }}/{{ container }}/override.conf {{ container }}/etc/systemd/system/freeradius.service.d/override.conf

- name: "{{ container }}: Push raddb files"
  shell: lxc file push -p -r {{ freeradius_config_dir }}/{{ freeradius_instance_name }} {{ container }}/etc/raddb/

- name: "{{ container }}: Push instance file"
  shell: lxc file push {{ freeradius_config_dir }}/{{ freeradius_instance_name }}.conf {{ container }}/etc/raddb/{{ freeradius_instance_name }}.conf

- name: "{{ container }}: Check if exists already dictionary.{{ freeradius_instance_name }} on dictionary"
  shell: lxc exec {{ container }} -- sh -c "cat /etc/raddb/dictionary | grep 'dictionary.{{ freeradius_instance_name }}' | wc -l"
  register: check_dictionary

- name: "{{ container }}: Add $INCLUDE to dictionary.{{ freeradius_instance_name }}"
  shell: lxc exec {{ container }} -- sh -c "echo '\$INCLUDE {{ freeradius_instance_name }}/dictionary.{{ freeradius_instance_name }}' >> /etc/raddb/dictionary"
  when: check_dictionary.stdout == "0"

- name: "{{ container }}: Fix radiusd files permssions"
  shell: lxc exec {{ container }} -- chown -R radius:radius /etc/raddb

- name: "{{ container }}: Reload systemd"
  shell: lxc exec {{ container }} -- systemctl daemon-reload

- name: "{{ container }}: Start Freeradius Service"
  shell: lxc exec {{ container }} -- systemctl restart freeradius
  when: freeradius_restart is defined

- name: "{{ container }}: Check if local certs directory exists"
  stat:
    path: "{{ freeradius_config_dir }}/certs"
  register: certs_dir

- name: "{{ container }}: Copy certs files"
  shell: lxc file push {{ freeradius_config_dir }}/certs/{server,ca,index,dh}* {{ container }}/etc/raddb/certs/
  when: certs_dir.stat.isdir is defined and certs_dir.stat.isdir

- name: "{{ container }}: Fix certs files permissions"
  shell: lxc exec {{ container }} -- sh -c "chown radius:radius -R /etc/raddb/certs && chmod 0600 /etc/raddb/certs/*"
  when: certs_dir.stat.isdir is defined and certs_dir.stat.isdir
